### ISSUE TITLE
Error: db - API not found: addNewAPI

### ISSUE THREAD

**Issue by Nulliik** [RossAscends/STMP#15]
https://github.com/RossAscends/STMP/commit/01866bd3614a650c807ea3b5340d678df76298d6 introduced error with adding API Endpoint tab. For me it is missing on clean setup and I have no way to use STMP now. The tab closes when you lauch the webpage and console says:
[2023-12-29T03:41:34.971] [ERROR] db - API not found: addNewAPI
[2023-12-29T03:41:34.972] [ERROR] server - Error parsing message: TypeError: Cannot read properties of null (reading 'name')

Howewer if you add custom API in commit before that one, and save DB file and open it in this version it works fine

**Comment by RossAscends** [comment]
this has probably been fixed in the past few days. git pull and try a clean install now

**Comment by Nulliik** [comment]
Confirming it is working now, though there is new issue with those instruction and author notes throwing errors when you won't type anything in there. Though if you type and remove it it works
